server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update # habilita atualizacao do banco pela api
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true # desabilita busca de metadados que o hibernate realiza no banco ao inicializar
    properties:
      hibernate:
        show_sql: true
